packages:
  - "shared/generated/typescript"
  - "shared/packages/*"
  - "shared/tools/*"
  - "extension"
  - "extension/packages/*"
  - "extension/test/*"

engineStrict: true
strictPeerDependencies: true
autoInstallPeers: false
savePrefix: "="
preferWorkspacePackages: true
sharedWorkspaceLockfile: true
resolutionMode: highest
verifyDepsBeforeRun: error
strictDepBuilds: true
cleanupUnusedCatalogs: true
